@startuml
/'
DOCUMENTACIÓN: https://plantuml.com/use-case-diagram
NOTA: GITHUB no renderiza este tipo de diagramas, sacar screenshot
'/

skinparam actorStyle awesome
"Usuario" as U

package Empresa {
left to right direction
usecase UC2 as (Cargar Prenda)
usecase UC3 as "Validar Prenda
--
Prenda No Valida"

U -> UC2
UC2 <- UC3 : <<includes>>
UC3 <.(Aviso de Información Faltante) :<<extends>> /'Posible cambio de nombre'/
UC3 <.(Aviso de Categoría Errónea) :<<extends>> /'Posible cambio de nombre'/

}
@enduml